default: &default
  adapter: postgresql
  encoding: unicode
  host: 127.0.0.1
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rails_api_development
  host: 127.0.0.1
  username: <%= ENV.fetch("DB_USERNAME") { "postgres" } %>
  password: <%= ENV.fetch("DB_PASSWORD") { "password" } %>

test:
  <<: *default
  database: rails_api_test

production:
  primary: &primary_production
    <<: *default
    database: rails_api_production
    username: postgres
    password:
  cache:
    <<: *primary_production
    database: rails_api_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: rails_api_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: rails_api_production_cable
    migrations_paths: db/cable_migrate
